
# The following paragraph was taken from the Apache Spark project.
#   see: https://github.com/apache/spark/blob/master/.github/autolabeler.yml
# Bot page: https://github.com/apps/probot-autolabeler
# The matching patterns follow the .gitignore spec.
# See: https://git-scm.com/docs/gitignore#_pattern_format
# Also, note that the plugin uses 'ignore' package. See also
# https://github.com/kaelzhang/node-ignore

INFRA:
  - ".baseline/"
  - ".github/"
  - ".asf.yaml"
  - ".gitattributes"
  - ".gitignore"
  - "baseline.gradle"
  - "deploy.gradle"
  - "jitpack.yml"
  - "site/mkdocs.yml"
  - "travis.yml"
BUILD:
  - "dev/"
  - "gradle/"
  - "**gradle"
BASH:
  - "dev/"
DOCS:
  - "site/"
  - "!/site/mkdocs.yml"
  - "**CHANGELOG.md"
  - "**README.md"
LICENSE:
  - "**LICENSE"
  - "**NOTICE"
EXAMPLES:
  - "examples/"
COMMON:
  - "common/"
API:
  - "api/"
CORE:
  - "**/core/"
  - "core/"
PYTHON:
  - "python/"
PARQUET:
  - "**/parquet/"
  - "parquet/"
ARROW:
  - "**/arrow/"
  - "arrow/"
ORC:
  - "**/orc/"
  - "orc/"
HIVE:
  - "**/hive/"
  - "hive/"
DATA:
  - "**/data/"
  - "data/"
SPARK:
  - "spark-runtime/"
  - "spark/"
  - "spark2/"
  - "spark3-runtime/"
  - "spark3/"
FLINK:
  - "**/flink/"
  - "flink/"
MR:
  - "mr/"
PIG:
  - "pig/"
