# Bot page: https://github.com/apps/probot-autolabeler
# The matching patterns follow the .gitignore spec.
# See: https://git-scm.com/docs/gitignore#_pattern_format
# Also, note that the plugin uses 'ignore' package. See also
# https://github.com/kaelzhang/node-ignore

INFRA:
  - ".baseline/"
  - ".github/"
  - "/dev/"
  - ".asf.yaml"
  - ".gitattributes"
  - ".gitignore"
  - "baseline.gradle"
  - "deploy.gradle"
  - "jitpack.yml"
  - "site/mkdocs.yml"
  - "travis.yml"
BUILD:
  - "/dev/"
  - "/project/"
  - "/assembly/"
  - "*pom.xml"
  - "/bin/docker-image-tool.sh"
  - "/bin/find-spark-home*"
  - "gradle/"
  - "**.gradle"
BASH:
  - "dev/check-license"
  - "**.sh
DOCS:
  - "site/"
  - "!/site/mkdocs.yml"
  - "**CHANGELOG.md"
  - "**LICENSE"
  - "**NOTICE"
  - "**README.md"
EXAMPLES:
  - "examples/"
COMMON:
  - "common/"
API:
  - "api/"
  - "python/iceberg/api/"
  - "python/tests/api/"
CORE:
  - "**/core/"
  - "core/"
  - "python/iceberg/core/"
  - "python/tests/core/"
PARQUET:
  - "**/parquet/"
  - "parquet/
ARROW:
  - "**/arrow/"
  - "arrow/"
ORC:
  - "**/orc/"
  - "orc/"
HIVE:
  - "**/hive/"
  - "hive/"
DATA:
  - "**/data/"
  - "data/"
SPARK2:
  - "spark-runtime/"
  - "spark/"
  - "spark2/"
SPARK3:
  - "spark3-runtime/"
  - "spark/"
  - "spark3/"
FLINK:
  - "**/flink/"
  - "flink/"
MR:
  - "mr/"
PIG:
  - "pig/"
