#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# The following paragraph was taken from the Apache Spark project.
#   see: https://github.com/apache/spark/blob/master/.github/autolabeler.yml
#
# Bot page: https://github.com/apps/probot-autolabeler
# The matching patterns follow the .gitignore spec.
# See: https://git-scm.com/docs/gitignore#_pattern_format
# Also, note that the plugin uses 'ignore' package. See also
# https://github.com/kaelzhang/node-ignore
INFRA:
  - "/.baseline"
  - "/.github"
  - "/dev"
  - ".asf.yaml"
  - ".gitattributes"
  - ".gitignore"
  - "baseline.gradle"
  - "deploy.gradle"
  - "jitpack.yml"
  - "travis.yml"
BUILD:
  - "*gradle*"
  - "versions.props"
DOCS:
  - "/site"
  - "**CHANGELOG.md"
  - "**README.md"
LICENSE:
  - "**LICENSE"
  - "**NOTICE"
EXAMPLES:
  - "/examples"
COMMON:
  - "/common"
API:
  - "/api"
CORE:
  - "/core"
PYTHON:
  - "/python"
PARQUET:
  - "/parquet"
ARROW:
  - "/arrow"
ORC:
  - "/orc"
HIVE:
  - "/hive3"
  - "/hive-metastore"
  - "/hive-runtime"
DATA:
  - "/data"
SPARK:
  - "/spark-runtime"
  - "/spark3-runtime"
  - "/spark"
  - "/spark2"
  - "/spark3"
FLINK:
  - "/flink-runtime"
  - "/flink"
MR:
  - "/mr"
PIG:
  - "/pig"

