#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
name: Iceberg Bug report 🐞
description: Problems, bugs and issues with Apache Iceberg
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: Apache Iceberg version
      description: What Apache Iceberg version are you using?
      multiple: false
      options:
        - "1.5.0 (latest release)"
        - "1.4.3"
        - "1.4.2"
        - "1.4.1"
        - "1.4.0"
        - "1.3.1"
        - "1.3.0"
        - "1.2.1"
        - "1.2.0"
        - "1.1.0"
        - "1.0.0"
        - "main (development)"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Query engine
      description: Which query engine?
      multiple: false
      options:
        - Spark
        - Trino
        - Starburst
        - Snowflake
        - Dremio
        - Starrocks
        - Doris
        - EMR
        - Athena
        - PrestoDB
        - Flink
        - Kafka Connect
        - Impala
        - Hive
        - Other
    validations:
      required: false
  - type: textarea
    attributes:
      label: Please describe the bug 🐞
      description: >
        Please describe the problem, what to expect, and how to reproduce.
        Feel free to include stacktraces and the Iceberg catalog configuration.
        You can include files by dragging and dropping them here.
    validations:
      required: true
