---
name: Iceberg Question
description: Questions around Apache Iceberg
labels: ["kind:question"]
body:
  - type: markdown
    attributes:
      value: "Feel free to ask your question on [Slack](https://join.slack.com/t/apache-iceberg/shared_invite/zt-2561tq9qr-UtISlHgsdY3Virs3Z2_btQ) as well."
  - type: textarea
    attributes:
      label: Query engine
      description: Which query engine (Flink, Spark, EMR, etc) are you using?
  - type: textarea
    attributes:
      label: Question
      description: What is your question?
    validations:
      required: true
