/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.iceberg.rest.events;

import java.util.Map;
import javax.annotation.Nullable;
import org.apache.iceberg.relocated.com.google.common.base.Preconditions;
import org.immutables.value.Value;

/**
 * Represents a catalog change event in the IRC Events endpoint.
 *
 * <p>Each event describes a single operation that occurred in the catalog, such as creating a table,
 * dropping a namespace, or updating a view.
 */
@Value.Immutable
public interface Event {

  /** Unique ID of this event. Clients should perform deduplication based on this ID. */
  String eventId();

  /**
   * Opaque ID of the request this event belongs to. Events from the same request share this ID.
   */
  String requestId();

  /** Total number of events generated by the same request. */
  int requestEventCount();

  /** Timestamp when this event occurred (epoch milliseconds). */
  long timestampMs();

  /**
   * The actor who performed the operation. The content is implementation-specific and may include
   * fields such as user name, service account, or other identifying information.
   */
  @Nullable
  Map<String, Object> actor();

  /** The operation that was performed. */
  CatalogOperation operation();

  @Value.Check
  default void validate() {
    Preconditions.checkArgument(eventId() != null, "Invalid event-id: null");
    Preconditions.checkArgument(requestId() != null, "Invalid request-id: null");
    Preconditions.checkArgument(requestEventCount() > 0, "request-event-count must be > 0");
    Preconditions.checkArgument(operation() != null, "Invalid operation: null");
  }
}
