#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Java CI Benchmark"
on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    paths-ignore:
    - '.github/workflows/python-ci.yml'
    - 'python/**'
    - 'python_legacy/**'
    - 'site/**'

jobs:
  run-benchmark:
    # if: contains(github.event.pull_request.labels.*.name, 'NESSIE')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark: ${{ github.event.pull_request.labels.*.name }}
    env:
      SPARK_LOCAL_IP: localhost
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts

    - name: Get Benchmark to run
      id: get_benchmark
      run: |
        # this first branch is only for testing
        if [[ "${{ matrix.benchmark }}" == "NESSIE" ]] ; then
          echo ::set-output name=BENCHMARK::VectorizedReadFlatParquetDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedListParquetDataWriteBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedListParquetDataWriteBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-SparkParquetReadersNestedDataBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IparkParquetReadersNestedDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-SparkParquetWritersFlatDataBenchmark')" ]] ; then
          echo ::set-output name=BENCHMARK::IparkParquetWritersFlatDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceFlatORCDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceFlatORCDataReadBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-SparkParquetReadersFlatDataBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IparkParquetReadersFlatDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-VectorizedReadDictionaryEncodedFlatParquetDataBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::VectorizedReadDictionaryEncodedFlatParquetDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedListORCDataWriteBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedListORCDataWriteBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-VectorizedReadFlatParquetDataBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::VectorizedReadFlatParquetDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceFlatParquetDataWriteBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceFlatParquetDataWriteBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedAvroDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedAvroDataReadBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceFlatAvroDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceFlatAvroDataReadBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedParquetDataWriteBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedParquetDataWriteBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedORCDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedORCDataReadBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceFlatParquetDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceFlatParquetDataReadBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceFlatParquetDataFilterBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceFlatParquetDataFilterBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedParquetDataFilterBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedParquetDataFilterBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-SparkParquetWritersNestedDataBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IparkParquetWritersNestedDataBenchmark
        elif [[ "${{ matrix.benchmark }}" == "benchmark-IcebergSourceNestedParquetDataReadBenchmark" ]] ; then
          echo ::set-output name=BENCHMARK::IcebergSourceNestedParquetDataReadBenchmark
        else
          echo "Cannot find benchmark to run"
          exit 0
        fi

    - run: ./gradlew :iceberg-spark3:jmh -PjmhIncludeRegex=${{ steps.get_benchmark.outputs.BENCHMARK }} -PjmhOutputPath=benchmark/${{ steps.get_benchmark.outputs.BENCHMARK }}.txt
    - uses: actions/upload-artifact@v2
      with:
        name: benchmark-results
        path: |
          **/benchmark/benchmark*.txt