#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Run License Check"
on:
  push:
    branches:
    - '**'
    - '!main'
    - '!0.*'
    - '!1.*'
    - '!2.*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.repository == 'apache/iceberg' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  rat:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
        persist-credentials: false
        repository: apache/iceberg
        ref: main
    - name: Sync fork branch with upstream main
      if: github.repository != 'apache/iceberg'
      run: |
        git fetch https://github.com/$GITHUB_REPOSITORY.git ${GITHUB_REF#refs/heads/}
        git -c user.name='Apache Iceberg' -c user.email='iceberg-ci@apache.org' merge --no-commit --progress --squash FETCH_HEAD
        git -c user.name='Apache Iceberg' -c user.email='iceberg-ci@apache.org' commit -m "Merged commit" --allow-empty
    - run: |
        dev/check-license
