# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Snapshot to Github Packages
on:
  release:
    types: [created, published, edited]
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo name with owner, such as apache/iceberg'
        required: true
        default: 'grepr/iceberg'
      ref:
        description: 'The branch name'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish iceberg-api package
        run: ./gradlew :iceberg-api:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-flink-2.0 package
        run: ./gradlew :iceberg-flink:iceberg-flink-2.0:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-core package
        run: ./gradlew :iceberg-core:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-data package
        run: ./gradlew :iceberg-data:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-hive-metastore package
        run: ./gradlew :iceberg-hive-metastore:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-parquet package
        run: ./gradlew :iceberg-parquet:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish iceberg-orc package
        run: ./gradlew :iceberg-orc:publishGreprPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}