/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.iceberg.data;

import java.util.List;
import java.util.Map;
import org.apache.iceberg.FileFormat;
import org.apache.iceberg.common.DynMethods;
import org.apache.iceberg.encryption.EncryptedOutputFile;
import org.apache.iceberg.io.AppenderBuilder;
import org.apache.iceberg.io.InputFile;
import org.apache.iceberg.io.ObjectModel;
import org.apache.iceberg.io.ReadBuilder;
import org.apache.iceberg.relocated.com.google.common.base.MoreObjects;
import org.apache.iceberg.relocated.com.google.common.base.Objects;
import org.apache.iceberg.relocated.com.google.common.collect.ImmutableList;
import org.apache.iceberg.relocated.com.google.common.collect.Maps;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Registry which provides the available {@link ReadBuilder}s and writer builders ({@link
 * AppenderBuilder}, {@link DataWriterBuilder}, {@link EqualityDeleteWriterBuilder}, {@link
 * PositionDeleteWriterBuilder}). Based on the `file format` and the requested `object model name`
 * the registry returns the correct reader and writer builders. These builders could be used to
 * generate the readers and writers.
 *
 * <p>The available {@link ObjectModel}s are registered by the {@link
 * #registerObjectModel(ObjectModel)} method. These {@link ObjectModel}s will be used to create the
 * {@link ReadBuilder}s and the {@link AppenderBuilder}s. The former ones are returned directly, the
 * later ones are wrapped in the appropriate writer builder implementations.
 */
public final class ObjectModelRegistry {
  private static final Logger LOG = LoggerFactory.getLogger(ObjectModelRegistry.class);
  // The list of classes which are used for registering the reader and writer builders
  private static final List<String> CLASSES_TO_REGISTER =
      ImmutableList.of(
          "org.apache.iceberg.arrow.vectorized.ArrowReader",
          "org.apache.iceberg.flink.data.FlinkObjectModels",
          "org.apache.iceberg.spark.source.SparkObjectModels");

  private static final Map<Key, ObjectModel<?>> OBJECT_MODELS = Maps.newConcurrentMap();

  /**
   * Registers a new object model.
   *
   * @param objectModel the object model
   * @throws IllegalArgumentException if an object model for the given {@code format} and {@code
   *     objectModelName} combination already exists
   */
  @SuppressWarnings("CatchBlockLogException")
  public static void registerObjectModel(ObjectModel<?> objectModel) {
    Key key = new Key(objectModel.format(), objectModel.name());
    if (OBJECT_MODELS.containsKey(key)) {
      throw new IllegalArgumentException(
          String.format(
              "Object model %s clashes with %s. Both serves %s",
              objectModel.getClass(), OBJECT_MODELS.get(key), key));
    }

    OBJECT_MODELS.put(key, objectModel);
  }

  @SuppressWarnings("CatchBlockLogException")
  private static void registerSupportedFormats() {
    // Uses dynamic methods to call the `register` for the listed classes
    for (String classToRegister : CLASSES_TO_REGISTER) {
      try {
        DynMethods.builder("register").impl(classToRegister).buildStaticChecked().invoke();
      } catch (NoSuchMethodException e) {
        // failing to register an object model is normal and does not require a stack trace
        LOG.info("Unable to register {} for data files: {}", classToRegister, e.getMessage());
      }
    }
  }

  static {
    registerSupportedFormats();
  }

  private ObjectModelRegistry() {}

  /**
   * Provides a reader builder for the given input file which returns objects generated by the given
   * object model.
   *
   * @param format of the file to read
   * @param objectModelName name of the object model used to generate the reader
   * @param inputFile to read
   * @return {@link ReadBuilder} for building the actual reader
   */
  public static ReadBuilder<?> readBuilder(
      FileFormat format, String objectModelName, InputFile inputFile) {
    return OBJECT_MODELS.get(new Key(format, objectModelName)).readBuilder(inputFile);
  }

  /**
   * Provides an appender builder for the given output file which writes a data file with a given
   * file format and expects input records defined by the object model.
   *
   * @param format of the file to write
   * @param objectModelName name of the object model used to generate the writer
   * @param outputFile to write
   * @param <E> type for the engine specific schema expected by the appender
   * @return {@link ReadBuilder} for building the actual reader
   */
  public static <E> AppenderBuilder<?, E> appenderBuilder(
      FileFormat format, String objectModelName, EncryptedOutputFile outputFile) {
    return ((ObjectModel<E>) OBJECT_MODELS.get(new Key(format, objectModelName)))
        .appenderBuilder(outputFile.encryptingOutputFile(), ObjectModel.WriteMode.DATA_WRITER);
  }

  /**
   * Provides a data writer builder for the given output file which writes a data file with a given
   * file format and expects input records defined by the object model.
   *
   * @param format of the file to write
   * @param objectModelName accepted by the writer
   * @param outputFile to write
   * @param <E> type for the engine specific schema expected by the writer
   * @return {@link ReadBuilder} for building the actual reader
   */
  public static <E> DataWriterBuilder<?, E> writerBuilder(
      FileFormat format, String objectModelName, EncryptedOutputFile outputFile) {
    return writerFor(format, objectModelName, outputFile, ObjectModel.WriteMode.DATA_WRITER);
  }

  /**
   * Provides an equality delete writer builder for the given output file which writes a delete file
   * with a given file format and expects input records defined by the object model.
   *
   * @param format of the file to write
   * @param objectModelName accepted by the writer
   * @param outputFile to write
   * @param <E> type for the engine specific schema expected by the writer
   * @return {@link ReadBuilder} for building the actual reader
   */
  public static <E> EqualityDeleteWriterBuilder<?, E> equalityDeleteWriterBuilder(
      FileFormat format, String objectModelName, EncryptedOutputFile outputFile) {
    return writerFor(
        format, objectModelName, outputFile, ObjectModel.WriteMode.EQUALITY_DELETE_WRITER);
  }

  /**
   * Provides a position delete writer builder for the given output file which writes a delete file
   * with a given file format and expects input records defined by the object model when the row
   * data is written.
   *
   * @param format of the file to write
   * @param objectModelName accepted by the writer
   * @param outputFile to write
   * @param <E> type for the engine specific schema expected by the writer
   * @return {@link ReadBuilder} for building the actual writer
   */
  public static <E> PositionDeleteWriterBuilder<?, E> positionDeleteWriterBuilder(
      FileFormat format, String objectModelName, EncryptedOutputFile outputFile) {
    return writerFor(
        format, objectModelName, outputFile, ObjectModel.WriteMode.POSITION_DELETE_WRITER);
  }

  @SuppressWarnings("unchecked")
  private static <B extends AppenderBuilder<B, E>, E> WriteBuilder<?, ?, E> writerFor(
      FileFormat format,
      String objectModelName,
      EncryptedOutputFile outputFile,
      ObjectModel.WriteMode mode) {
    return new WriteBuilder<>(
        ((ObjectModel<E>) OBJECT_MODELS.get(new Key(format, objectModelName)))
            .<B>appenderBuilder(outputFile.encryptingOutputFile(), mode),
        outputFile.encryptingOutputFile().location(),
        format);
  }

  /** Key used to identify readers and writers in the {@link ObjectModelRegistry}. */
  private static class Key {
    private final FileFormat fileFormat;
    private final String objectModelName;

    private Key(FileFormat fileFormat, String objectModelName) {
      this.fileFormat = fileFormat;
      this.objectModelName = objectModelName;
    }

    @Override
    public String toString() {
      return MoreObjects.toStringHelper(this)
          .add("fileFormat", fileFormat)
          .add("objectModelName", objectModelName)
          .toString();
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }

      if (!(o instanceof Key)) {
        return false;
      }

      Key other = (Key) o;
      return Objects.equal(other.fileFormat, fileFormat)
          && Objects.equal(other.objectModelName, objectModelName);
    }

    @Override
    public int hashCode() {
      return Objects.hashCode(fileFormat, objectModelName);
    }
  }
}
